import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css';
import { cn } from '@/lib/utils';
import Header from './Component/Header';
import Footer from './Component/Footer';
// import SocialIcons from './Component/SocialIcons';
import SocialIcons from './Component/Socialicons';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='light'>
      <body className={cn(
        'min-h-screen font-sans antialiased',
        inter.className
      )}>
        <Header/>
        {children}
        <Footer/>
        <SocialIcons/>
        </body>
    </html>
  )
}
